name: Koobalution
favicon: null
layout_spectrum: 0.23278
typography_spectrum: 0.66601
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9375
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
